version: 2

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    
    steps:
      - checkout
      
      - restore_cache:
          name: my cache
          keys: 
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # Fallback to using the latest cache if no exec match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv ~/.dockerproj
            source ~/.dockerproj/bin/activate
            ls -al 
            make install
            # Install hadolint
            echo Hello world
            wget -O ~/.dockerproj/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                            chmod +x ~/.dockerproj/bin/hadolint

      - save_cache:
           paths: 
             - ~/.dockerproj
           key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run lint
          command: |
            . ~/.dockerproj/bin/activate
            make lint


